### ISSUE TITLE
Make Code PEP8 compliant 

### ISSUE THREAD

**Issue by saurabhjn76** [saurabhjn76/Race-the-car#7]
The current code is not as per PEP8 guidelines:
![screen shot 2018-10-18 at 9 41 18 pm](https://user-images.githubusercontent.com/9781788/47168457-98276b80-d31e-11e8-8819-555fe0bbefda.png)
Make the code to follow PEP8 coding standards.
http://pep8online.com/checkresult

**Comment by GregorGrasselli** [comment]
solved in #10

**Comment by saurabhjn76** [comment]
Thanks @GregorGrasselli
